version: "3.7"

services:
  app:
    image: mybooks
    container_name: "mybooks-container"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      TZ: "Asia/Seoul"

  redis:
    image: redis:7.2.3
    container_name: "redis-container"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
      - "./redis/conf/redis.conf:/usr/local/conf/redis.conf"
    command:
      - "redis-server /usr/local/conf/redis.conf"


