version: "3.7"

services:
  app:
    image: mybooks
    container_name: "mybooks-container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      TZ: "Asia/Seoul"

  redis:
    image: redis:7.2.3
    expose: ["6379"]
    container_name: "redis-container"
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis.conf"]