version: "3.7"

services:
  app:
    image: mybooks
    container_name: "mybooks-container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILES_ACTIVE: "production"

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: "mysql-container"
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mybooks
      TZ: Asia/Seoul
    volumes:
      - "./mysql:/var/lib/mysql"

  redis:
    image: redis:7.2.3
    restart: unless-stopped
    expose: ["6379"]
    container_name: "redis-container"
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis.conf"]